import Head from 'next/head';
import Event from '../src/components/Event';
import Hero from '../src/components/Hero';
import Navigation from '../src/components/Navigation';


export default function Home() {

  return (
    <div className="">
      <Head>
        <title>React Conference</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="bg-gradient-to-r from-sky-100 via-transparent to-pink-100">
    <Navigation/>
    <Hero/>
    </div>
    <Event/>
   
    
    </div>
  )
}
